import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
// Google Cloud Run injects the PORT environment variable (defaults to 8080)
const PORT = process.env.PORT || 8080;

// Serve static files from the 'dist' directory (generated by 'npm run build')
app.use(express.static(path.join(__dirname, 'dist')));

// Handle Single Page Application (SPA) routing
// If a user goes to /about directly, serve index.html so React can handle the route
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

// Start the server and listen on 0.0.0.0 to ensure external access in the container
app.listen(PORT, '0.0.0.0', () => {
  console.log(`Server is running on port ${PORT}`);
});